"""Initial quotes table

Revision ID: b34761c88524
Revises:
Create Date: 2025-07-12 16:24:46.874102

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "b34761c88524"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    # Only create table if it doesn't exist (handles pre-existing databases)
    if "quotes" not in tables:
        op.create_table(
            "quotes",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("content", sa.Text(), nullable=False),
            sa.Column("author", sa.String(length=255), nullable=False),
            sa.Column("added_by", sa.Integer(), nullable=False),
            sa.Column("guild_id", sa.Integer(), nullable=False),
            sa.Column("channel_id", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("original_timestamp", sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_quotes_channel_id"), "quotes", ["channel_id"], unique=False
        )
        op.create_index(
            op.f("ix_quotes_guild_id"), "quotes", ["guild_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quotes_guild_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_channel_id"), table_name="quotes")
    op.drop_table("quotes")
    # ### end Alembic commands ###
